# Arquivo de Manifesto do Cargo
# Define as configurações e dependências do projeto Rust.

[package]
name = "extrator_gpx"
version = "0.1.0"
edition = "2021"

# Seção de dependências.
[dependencies]
gpx = "0.10.0"
ffprobe = "0.4.0"
chrono = "0.4"

# Dependências para desenho e manipulação de imagens
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"

# Novas dependências para o Servidor Web (Backend)
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["multipart"] }
tower-http = { version = "0.5.0", features = ["fs", "cors"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.8", features = ["v4"] }
